[package]
name = "custom-completion-zsh"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
