[package]
name = "custom-completion-zsh"
version = "0.1.4"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
clap_complete = "4.5.57"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
